services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: db_cariri
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpostgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_cariri"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./database:/app/database  
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: